# Generated by Django 5.2.4 on 2025-07-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('measurements', models.JSONField(default=dict)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('wisdom', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['device_id', 'received_at'], name='ttn_app_sen_device__baee83_idx')],
            },
        ),
    ]
